# Generated by Django 5.1.4 on 2024-12-18 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErishilganYutuqlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='yutuqlar/', verbose_name='Asosiy Rasm')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan Sana')),
            ],
            options={
                'verbose_name': 'Erishilgan Yutuq',
                'verbose_name_plural': 'Erishilgan Yutuqlar',
            },
        ),
        migrations.CreateModel(
            name='ErishilganYutuqRasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yutuqlar/', verbose_name='Yutuq Rasmi')),
                ('yutuq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='news_app.erishilganyutuqlar', verbose_name='Tegishli Yutuq')),
            ],
            options={
                'verbose_name': 'Yutuq Rasmi',
                'verbose_name_plural': 'Yutuq Rasmlari',
            },
        ),
    ]
