# Generated by Django 5.1.4 on 2024-12-18 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatbuotXizmati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='matbuot/', verbose_name='Asosiy Rasm')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan Sana')),
            ],
            options={
                'verbose_name': 'Matbuot Xizmati',
                'verbose_name_plural': 'Matbuot Xizmati',
            },
        ),
        migrations.CreateModel(
            name='MatbuotXizmatiRasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='matbuot/', verbose_name='Matbuot Rasmi')),
                ('yutuq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='news_app.matbuotxizmati', verbose_name='Tegishli Matbuot')),
            ],
            options={
                'verbose_name': 'Matbuot Xizmati Rasmi',
                'verbose_name_plural': 'Matbuot Xizmati Rasmlari',
            },
        ),
    ]
