# Generated by Django 5.1.4 on 2024-12-18 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_matbuotxizmati_matbuotxizmatirasmlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElonVaTadbirlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='elon_va_tadbirlar/', verbose_name='Asosiy Rasm')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan Sana')),
            ],
            options={
                'verbose_name': 'Elon va Tadbir',
                'verbose_name_plural': 'Elon va Tadbirlar',
            },
        ),
        migrations.CreateModel(
            name='ElonVaTadbirlarRasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='elon_va_tadbirlar/', verbose_name='Elon va Tadbir Rasmi')),
                ('elon_tadbir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='news_app.elonvatadbirlar', verbose_name='Tegishli Elon yoki Tadbir')),
            ],
            options={
                'verbose_name': 'Elon va Tadbir Rasmi',
                'verbose_name_plural': 'Elon va Tadbir Rasmlari',
            },
        ),
    ]
