# Generated by Django 5.1.4 on 2024-12-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_elonvatadbirlar_elonvatadbirlarrasmlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elonvatadbirlar',
            options={'ordering': ['-id'], 'verbose_name': 'Elon va Tadbir', 'verbose_name_plural': 'Elon va Tadbirlar'},
        ),
        migrations.AlterModelOptions(
            name='erishilganyutuqlar',
            options={'ordering': ['-id'], 'verbose_name': 'Erishilgan Yutuq', 'verbose_name_plural': 'Erishilgan Yutuqlar'},
        ),
        migrations.AlterModelOptions(
            name='matbuotxizmati',
            options={'ordering': ['-id'], 'verbose_name': 'Matbuot Xizmati', 'verbose_name_plural': 'Matbuot Xizmati'},
        ),
    ]
